# Start with Node.js base image for building the application
FROM node:18 as builder

# Set the working directory in the container
RUN mkdir -p /usr/src/app/build && chown -R node:node /usr/src/app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# Build the app
RUN npm run build
